# Generated by Django 4.2.12 on 2024-05-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devedor_cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('devedor_nome', models.CharField(max_length=60)),
                ('valor', models.CharField(max_length=10)),
                ('chave', models.CharField(blank=True, max_length=77, null=True)),
                ('descricao', models.CharField(max_length=140)),
                ('expiracao', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('txid', models.CharField(max_length=50)),
                ('pix_code', models.CharField(max_length=50)),
                ('qrcode_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
